### ISSUE TITLE
Fail on train-ticket

### ISSUE THREAD

**Issue by svacina** [cloudhubs/prophet-utils-app#7]
System fails to analyze train-ticket.

Request:

```
{
	"repositories": [
		{
			"path": "https://github.com/FudanSELab/train-ticket",
			"isMonolith": false
		}
	],
	"systemName" : "tms"
}
```

Received response:

```
{
    "global": null,
    "ms": null
}
```

Expected response:

Not null.

**Comment by svacina** [comment]
Log from the app:

```
Cloning https://github.com/cloudhubs/train-ticket into repos-1587775012/train-ticket
Completed Cloning
Failed to process project!
```

**Comment by vinbush** [comment]
I am unable to replicate this error. Does it still happen with the latest 0.0.8-dev versions of utils-app, utils, and dto?

**Comment by vinbush** [comment]
Resolved, should no longer return nulls for anything unless an error is indicated (no Java, can't clone, etc.)
